### ISSUE TITLE
PCL compile error

### ISSUE THREAD

**Issue by bluetulip89** [BlackMamba591/Object_Recognition#2]
While giving catkin_make, I am getting the following error , Kindly help in resolving it . 

In ../src/object_recognition/src/global_hypothesis_verification.cpp:249:20: error: ‘class pcl::UniformSampling<pcl::PointXYZRGBA>’ has no member named ‘compute’
   uniform_sampling.compute(keypointIndices2);

**Comment by arunavanag591** [comment]
I suspect you might be using a newer version of PCL library. This piece of code was written in the year 2015. A google search gave me this which talks about the pcl 1.8: http://www.pcl-users.org/UniformSampling-has-no-member-named-compute-td4043796.html

Please check through and update the code. Hopefully, that may resolve the issue.

**Comment by bluetulip89** [comment]
Thanks for the reply. As you rightly said I am using a new PCL library. I changed and now it's working fine. If you approve then I will do a commit and add the updated code. thanks again

**Comment by arunavanag591** [comment]
That will be great if you could please. Please create a pull request to branch develop.
