### ISSUE TITLE
question regarding pose information

### ISSUE THREAD

**Issue by npd26** [BlackMamba591/Object_Recognition#3]
Hi,

as object recognition, in correspondence grouping ant other method) output the pose information w.r.t to input .pcd file but for for robotic arm manipulation, isn't we require pose in camera_frame? or am I understanding wrong here?  also, what should be object pose related to? should I define object origin in .pcd file(to that camera_frame relate to)?

thanks.

**Comment by arunavanag591** [comment]
You need pose in robot frame. The object recognition pose is basically with respect to the camera frame and your reference object. Once the pose is found, it needs to be transformed into your robot joint angles for which you may consider using move it.
